# Generated by Django 4.2.1 on 2023-05-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='altaEnsayos',
            fields=[
                ('IDaltaEnsayos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreSolicitante', models.CharField(max_length=100)),
                ('areaSolicitante', models.CharField(max_length=100)),
                ('fechaSolicitud', models.DateField()),
                ('proyecto', models.CharField(max_length=100)),
                ('claveEnsayo', models.CharField(max_length=100)),
                ('nombreEnsayo', models.CharField(max_length=100)),
                ('ensayooperfil', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('tipoMuestra', models.CharField(max_length=100)),
                ('condiciones', models.CharField(max_length=100)),
                ('motivosRechazo', models.CharField(max_length=100)),
                ('tiempoEntrega', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'altaEnsayos',
            },
        ),
        migrations.CreateModel(
            name='altaInter',
            fields=[
                ('IDaltaInter', models.IntegerField(primary_key=True, serialize=False)),
                ('ensayo', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('analizador', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'altaInter',
            },
        ),
        migrations.CreateModel(
            name='valoresRef',
            fields=[
                ('IDvaloresRef', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreSolicitante', models.CharField(max_length=100)),
                ('fechaSolicitud', models.DateField()),
                ('area', models.CharField(max_length=100)),
                ('sistema', models.CharField(max_length=100)),
                ('anexos', models.CharField(max_length=100)),
                ('claveCatalogo', models.CharField(max_length=100)),
                ('labSubrogacion', models.CharField(max_length=100)),
                ('ensayo', models.CharField(max_length=100)),
                ('motivodecambios', models.CharField(max_length=100)),
                ('cambio', models.CharField(max_length=100)),
                ('metodologia', models.CharField(max_length=100)),
                ('unidades', models.CharField(max_length=100)),
                ('ValoresReferencia', models.TextField()),
            ],
            options={
                'db_table': 'valoresRef',
            },
        ),
    ]
