# Generated by Django 4.2.1 on 2023-05-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='altaensayos',
            name='opciones',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
