# Generated by Django 4.2.1 on 2023-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_altaensayos_opciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='altaEnsayos2',
            fields=[
                ('IDaltaEnsayos2', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreSolicitante', models.CharField(max_length=100)),
                ('areaSolicitante', models.CharField(max_length=100)),
                ('fechaSolicitud', models.DateField()),
                ('intercambio', models.CharField(max_length=100)),
                ('porCobrar', models.CharField(max_length=100)),
                ('pasteur', models.CharField(max_length=100)),
                ('modulab', models.CharField(max_length=100)),
                ('proyecto', models.CharField(max_length=100)),
                ('claveEnsayo', models.CharField(max_length=100)),
                ('nombreEnsayo', models.CharField(max_length=100)),
                ('ensayooperfil', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('tipoMuestra', models.CharField(max_length=100)),
                ('condiciones', models.CharField(max_length=100)),
                ('motivosRechazo', models.CharField(max_length=100)),
                ('tiempoEntrega', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'altaEnsayos2',
            },
        ),
    ]
